dist: trusty
language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler
env:
  matrix:
    - SUITE=mysql
    - SUITE=pg
    - SUITE=sqlite3
rvm:
  - 2.2.3
  - 2.3.4
  - '2.4'

matrix:
  fast_finish: true
  include:
    - rvm: 2.2.3
      env: SUITE=rubocop

notifications:
  email: false
services:
  - redis
bundler_args: --without deploy production debug --jobs 3 --retry 3
